{% set data = load_setup_py_data() %}

package:
    name: singlestore
    version: {{ data.get('version') }}

source:
    path: ..

build:
    noarch: python
    number: {{ PACKAGE_BUILD_NUMBER }}
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python {{ python }}
        - pip
    run:
        - python
        - mysql-connector-python
        - requests
        - sqlparams

test:
    imports:
        - singlestore
    requires:
        - coverage
        - nose2
        - pandas
    commands:
        - nose2 -v singlestore.tests.test_basics

about:
    home: https://github.com/singlestore-labs/singlestore-python
    license: Apache 2.0
    license_file: ../LICENSE
    summary: SingleStore Database Interface
    doc_url: https://singlestore-labs.github.io/singlestore-python/index.html
    dev_url: https://github.com/singlestore-labs/singlestore-python
