name: Coverage tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    services:
      singlestore:
        image: ghcr.io/singlestore-labs/singlestoredb-dev:latest
        ports:
          - 3306:3306
          - 8080:8080
          - 9000:9000
        env:
          SINGLESTORE_LICENSE: ${{ secrets.SINGLESTORE_LICENSE }}
          ROOT_PASSWORD: "root"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Create test databases
        run: |
          mysql -h 127.0.0.1 -u root --password=root -e 'create database if not exists pymysqlsv_test1'
          mysql -h 127.0.0.1 -u root --password=root -e 'create database if not exists pymysqlsv_test2'

      - name: Install SingleStore package
        run: |
          python setup.py install

      - name: Run MySQL protocol tests
        run: |
          pytest -q --cov=singlestoredb --cov-report=xml:coverage-mysql.xml singlestoredb/tests singlestoredb/clients/pymysqlsv/tests
        env:
          SINGLESTOREDB_URL: "root:root@127.0.0.1:3306"
          SINGLESTOREDB_MANAGEMENT_TOKEN: ${{ secrets.CLUSTER_API_KEY }}

      - name: Run MySQL protocol tests (pure Python)
        run: |
          pytest -q --cov=singlestoredb --cov-report=xml:coverage-mysql-py.xml singlestoredb/tests singlestoredb/clients/pymysqlsv/tests
        env:
          SINGLESTOREDB_URL: "root:root@127.0.0.1:3306"
          SINGLESTOREDB_PURE_PYTHON: 1
          SINGLESTOREDB_MANAGEMENT_TOKEN: ${{ secrets.CLUSTER_API_KEY }}

      - name: Run HTTP protocol tests
        run: |
          pytest -q --cov=singlestoredb --cov-report=xml:coverage-http.xml singlestoredb/tests
        env:
          SINGLESTOREDB_URL: "http://root:root@127.0.0.1:9000"
          SINGLESTOREDB_MANAGEMENT_TOKEN: ${{ secrets.CLUSTER_API_KEY }}
          # Can not change databases using HTTP API. The URL below will be
          # used to create the database and the generated database name will
          # be applied to the above URL.
          SINGLESTOREDB_INIT_DB_URL: "root:root@127.0.0.1:3306"

      - name: Generate report
        run: |
          coverage combine coverage-mysql.xml coverage-http.xml coverage-mysql-py.xml
          coverage report
          coverage xml
          coverage html
