name: Run unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  container-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        s2-driver: [pymysql]
        s2-port: [3306]
        include:
          - python-version: "3.10"
            s2-driver: http
            s2-port: 9000

    services:
      singlestore:
        image: singlestore/cluster-in-a-box:latest
        ports:
          - 3306:3306
          - 8080:8080
          - 9000:9000
        env:
          LICENSE_KEY: ${{ secrets.SINGLESTORE_LICENSE }}
          ROOT_PASSWORD: "root"
          START_AFTER_INIT: "Y"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nose2

      - name: Install SingleStore package
        run: |
          python setup.py install

      - name: Initialize database
        run: python singlestore/tests/init_db.py
        env:
          SINGLESTORE_URL: "pymysql://root:root@localhost:3306"

      - name: Run tests
        run: nose2 -v singlestore.tests
        env:
          SINGLESTORE_URL: "${{ matrix.s2-driver }}://root:root@localhost:${{ matrix.s2-port }}/app"
