name: Run unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  container-job:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
        singlestore-url:
          - mysqldb://root:root@127.0.0.1:3306/app
          - pymysql://root:root@127.0.0.1:3306/app
          - http://root:root@127.0.0.1:9000/app

    services:
      singlestore:
        image: singlestore/cluster-in-a-box:latest
        ports:
          - 3306:3306
          - 8080:8080
          - 9000:9000
        env:
          LICENSE_KEY: ${{ secrets.SINGLESTORE_LICENSE }}
          ROOT_PASSWORD: "root"
          START_AFTER_INIT: "Y"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nose2
          pip install mysqlclient

      - name: Install SingleStore package
        run: |
          python setup.py install

#     - name: Initialize database
#       run: python singlestore/tests/init_db.py
#       env:
#         SINGLESTORE_URL: "pymysql://root:root@127.0.0.1:3306"

      - name: Initialize database
        run: mysql --user=root --password=root --host=127.0.0.1 --port=3306 --default-auth=mysql_native_password < resources/test.sql

      - name: Run tests
        run: nose2 -v singlestore.tests
        env:
          SINGLESTORE_URL: "${{ matrix.singlestore-url }}"
          SINGLESTORE_HTTP_PORT: 9000
