name: Run unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  container-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    services:
      singlestore:
        image: singlestore/cluster-in-a-box:latest
        ports:
          - 3306:3306
          - 8080:8080
        env:
          LICENSE_KEY: ${SINGLESTORE_LICENSE}
          ROOT_PASSWORD: "root"
          START_AFTER_INIT: "Y"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nose
      - name: Run tests
        run: |
          nosetests .
        env:
          SINGLESTORE_URL: "mysqldb://root:root@127.0.0.1:3306/app"
          LICENSE_KEY: ${SINGLESTORE_LICENSE}
          ROOT_PASSWORD: "root"
          START_AFTER_INIT: "Y"
