name: Smoke test

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:


jobs:

  setup-database:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Initialize database
        id: initialize-database
        run: |
          PYTHONPATH="$GITHUB_WORKSPACE" python resources/create_test_cluster.py --password=${{ secrets.CLUSTER_PASSWORD }} --token=${{ secrets.CLUSTER_API_KEY }} --init-sql resources/test.sql "$GITHUB_WORKFLOW" > cluster_info.txt
          echo "::set-output name=cluster-id::$(cat cluster_info.txt | cut -d' ' -f1 $cluster_info)"
          echo "::set-output name=cluster-host::$(cat cluster_info.txt | cut -d' ' -f2 $cluster_info)"

    outputs:
      cluster-id: ${{ steps.initialize-database.outputs.cluster-id }}
      cluster-host: ${{ steps.initialize-database.outputs.cluster-host }}


  smoke-test:
    needs: setup-database

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        driver:
          - cymysql
          - pymysql
          - mysqldb
#         - http

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install MySQL libraries
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew update
          brew install mysql

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Install SingleStore package
        run: |
          python setup.py install

      - name: Run tests
        if: ${{ matrix.driver != 'http' }}
        run: nose2 -v singlestore.tests.test_basics
        env:
          SINGLESTORE_URL: "${{ matrix.driver }}://${{ secrets.CLUSTER_USER }}:${{ secrets.CLUSTER_PASSWORD }}@${{ needs.setup-database.outputs.cluster-host }}:3306/app"

      - name: Run tests
        if: ${{ matrix.driver == 'http' }}
        run: nose2 -v singlestore.tests.test_basics
        env:
          SINGLESTORE_URL: "${{ matrix.driver }}://${{ secrets.CLUSTER_USER }}:${{ secrets.CLUSTER_PASSWORD }}@${{ needs.setup-database.outputs.cluster-host }}:8080/app"


  shutdown-database:
    needs: [setup-database, smoke-test]
    if: ${{ always() }}
    runs-on: ubuntu-latest

    steps:
      - name: Shutdown database
        run: |
          python resources/drop_test_cluster.py --token=${{ secrets.CLUSTER_API_KEY }} $CLUSTER_ID
        env:
          CLUSTER_ID: ${{ needs.setup-database.outputs.cluster-id }}
