name: Smoke test

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:


jobs:

  setup-database:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Initialize database
        run: |
          cat resources/test.sql | mysql --user="${{ secrets.CLUSTER_USER }}" --password="${{ secrets.CLUSTER_PASSWORD }}" --host="${{ secrets.CLUSTER_HOST }}" --port=3306 --default-auth=mysql_native_password
#         sed 's/{PORT}/9000/' resources/http_api.sql | mysql --user="${{ secrets.CLUSTER_USER }}" --password="${{ secrets.CLUSTER_PASSWORD }}" --host="${{ secrets.CLUSTER_HOST }}" --port=3306 --default-auth=mysql_native_password


  smoke-test:
    needs: setup-database

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        driver:
          - cymysql
          - pymysql
          - mysqldb
#         - http

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install MySQL libraries
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew update
          brew install mysql

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Install SingleStore package
        run: |
          python setup.py install

      - name: Run tests
        if: ${{ matrix.driver != 'http' }}
        run: nose2 -v singlestore.tests.test_basics
        env:
          SINGLESTORE_URL: "${{ matrix.driver }}://${{ secrets.CLUSTER_USER }}:${{ secrets.CLUSTER_PASSWORD }}@${{ secrets.CLUSTER_HOST }}:3306/app"

      - name: Run tests
        if: ${{ matrix.driver == 'http' }}
        run: nose2 -v singlestore.tests.test_basics
        env:
          SINGLESTORE_URL: "${{ matrix.driver }}://${{ secrets.CLUSTER_USER }}:${{ secrets.CLUSTER_PASSWORD }}@${{ secrets.CLUSTER_HOST }}:8080/app"
