name: Smoke test

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:


jobs:

  setup-database:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pymysql

      - name: Initialize database
        id: initialize-database
        run: |
          python resources/create_test_cluster.py --password="${{ secrets.CLUSTER_PASSWORD }}" --token="${{ secrets.CLUSTER_API_KEY }}" --init-sql singlestoredb/tests/test.sql --output=github --expires=2h "singlestore-python - $GITHUB_WORKFLOW"
        env:
          PYTHONPATH: ${{ github.workspace }}

    outputs:
      cluster-id: ${{ steps.initialize-database.outputs.cluster-id }}
      cluster-host: ${{ steps.initialize-database.outputs.cluster-host }}
      cluster-database: ${{ steps.initialize-database.outputs.cluster-database }}


  smoke-test:
    needs: setup-database

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        driver:
          - mysql
          - https
        pure-python:
          - 0
        # Manually include a couple of runs on Mac & Windows
        include:
          - os: ubuntu-latest
            python-version: "3.9"
            driver: mysql
            pure-python: 1
          - os: macos-latest
            python-version: "3.9"
            driver: mysql
            pure-python: 0
          - os: macos-latest
            python-version: "3.9"
            driver: https
            pure-python: 0
          - os: windows-latest
            python-version: "3.9"
            driver: mysql
            pure-python: 0
          - os: windows-latest
            python-version: "3.9"
            driver: https
            pure-python: 0

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt
          pip install mysqlclient wheel

      - name: Install SingleStore package
        run: |
          python setup.py install

      - name: Run tests
        if: ${{ matrix.driver != 'https' }}
        run: pytest -q singlestoredb/tests/test_basics.py
        env:
          SINGLESTOREDB_URL: "${{ matrix.driver }}://${{ secrets.CLUSTER_USER }}:${{ secrets.CLUSTER_PASSWORD }}@${{ needs.setup-database.outputs.cluster-host }}:3306/${{ needs.setup-database.outputs.cluster-database }}?pure_python=${{matrix.pure-python}}"

      - name: Run tests
        if: ${{ matrix.driver == 'https' }}
        run: pytest -q singlestoredb/tests/test_basics.py
        env:
          SINGLESTOREDB_URL: "${{ matrix.driver }}://${{ secrets.CLUSTER_USER }}:${{ secrets.CLUSTER_PASSWORD }}@${{ needs.setup-database.outputs.cluster-host }}:9000/${{ needs.setup-database.outputs.cluster-database }}?pure_python=${{matrix.pure-python}}"


  shutdown-database:
    needs: [setup-database, smoke-test]
    if: ${{ always() }}
    runs-on: ubuntu-latest

    steps:
      # Just use curl here so we don't have to check out the package source again.
      - name: Shutdown database
        run: |
          curl -H "Accept: application/json" -H "Authorization: Bearer ${{ secrets.CLUSTER_API_KEY }}" -X DELETE "https://api.singlestore.com/v0beta/clusters/${{ env.CLUSTER_ID }}"
        env:
          CLUSTER_ID: ${{ needs.setup-database.outputs.cluster-id }}
