name: Run smoke tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  setup-database:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Initialize database
        run: |
          mysql --user=admin --password="${{ secrets.CLUSTER_PASSWORD }}" --host=svc-fce74933-486c-4ce7-9580-dceb7819bb70-ddl.aws-oregon-2.svc.singlestore.com --port=3306 --default-auth=mysql_native_password < resources/test.sql


  smoke-test:
    needs: setup-database

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
#         - "3.7"
#         - "3.8"
#         - "3.9"
          - "3.10"
        singlestore-url:
          - cymysql://svc-fce74933-486c-4ce7-9580-dceb7819bb70-ddl.aws-oregon-2.svc.singlestore.com:3306
          - pymysql://svc-fce74933-486c-4ce7-9580-dceb7819bb70-ddl.aws-oregon-2.svc.singlestore.com:3306
          - mysqldb://svc-fce74933-486c-4ce7-9580-dceb7819bb70-ddl.aws-oregon-2.svc.singlestore.com:3306
#         - mysqldb://root:root@127.0.0.1:3306
#         - pymysql://root:root@127.0.0.1:3306
#         - cymysql://root:root@127.0.0.1:3306
#         - http://root:root@127.0.0.1:9000

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Install MySQL libraries
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew update
          brew install mysql

      - name: Install SingleStore package
        run: |
          python setup.py install

      - name: Run tests
        run: nose2 -v singlestore.tests
        env:
          SINGLESTORE_URL: "${{ matrix.singlestore-url }}/app"
          SINGLESTORE_USER: "admin"
          SINGLESTORE_PASSWORD: "${{ secrets.CLUSTER_PASSWORD }}"
