name: Run smoke tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
#         - "3.7"
#         - "3.8"
#         - "3.9"
          - "3.10"
        singlestore-url:
          - "mysqldb://admin:${{ secrets.CLUSTER_PASSWORD }}@svc-fce74933-486c-4ce7-9580-dceb7819bb70-ddl.aws-oregon-2.svc.singlestore.com:3306"
#         - mysqldb://root:root@127.0.0.1:3306
#         - pymysql://root:root@127.0.0.1:3306
#         - cymysql://root:root@127.0.0.1:3306
#         - http://root:root@127.0.0.1:9000

#   services:
#     singlestore:
#       image: singlestore/cluster-in-a-box:latest
#       ports:
#         - 3306:3306
#         - 8080:8080
#         - 9000:9000
#       env:
#         LICENSE_KEY: ${{ secrets.SINGLESTORE_LICENSE }}
#         ROOT_PASSWORD: "root"
#         START_AFTER_INIT: "Y"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Install SingleStore package
        run: |
          python setup.py install

      - name: Initialize database
        run: python singlestore/tests/init_db.py
        env:
          # Always use PyMySQL; HTTP doesn't support connections with out a db name.
#         SINGLESTORE_URL: "pymysql://root:root@127.0.0.1:3306"
          SINGLESTORE_URL: "pymysql://admin:${{ secrets.CLUSTER_PASSWORD }}@svc-fce74933-486c-4ce7-9580-dceb7819bb70-ddl.aws-oregon-2.svc.singlestore.com:3306"

      - name: Run tests
        run: nose2 -v singlestore.tests
        env:
          SINGLESTORE_URL: "${{ matrix.singlestore-url }}/app"
